id = "mlir"
name = "MLIR"
description = "MLIR support (third-party)"
version = "0.3.0"
schema_version = 1
authors = ["Buyun Xu <xubuyun@outlook.com>"]
repository = "https://github.com/felixtensor/zed-mlir"

[grammars.mlir]
repository = "https://github.com/felixtensor/tree-sitter-mlir"
rev = "75c6831e4511f9a01e02085fa8608f6662fb9604"

[grammars.tablegen]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-tablegen"
rev = "b1170880c61355aaf38fc06f4af7d3c55abdabc4"
