id = "mlir-suite"
name = "MLIR Suite"
description = "MLIR, TableGen, and PDLL with integrated LSP servers and custom dialect support."
version = "0.5.0"
schema_version = 1
authors = ["Buyun Xu <xubuyun@outlook.com>"]
repository = "https://github.com/felixtensor/zed-mlir"

[grammars.mlir]
repository = "https://github.com/felixtensor/tree-sitter-mlir"
commit = "79b1576d428873eb2bb8c90079677210843952c7"

[grammars.tablegen]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-tablegen"
commit = "b1170880c61355aaf38fc06f4af7d3c55abdabc4"

[grammars.pdll]
repository = "https://github.com/felixtensor/tree-sitter-pdll"
commit = "8c7e8643acc5534b4e5316e2c97aa52a54d74faa"

[language_servers.mlir-lsp-server]
name = "mlir-lsp-server"
language = "MLIR"

[language_servers.mlir-pdll-lsp-server]
name = "mlir-pdll-lsp-server"
language = "PDLL"

[language_servers.tblgen-lsp-server]
name = "tblgen-lsp-server"
language = "TableGen"
