id = "mlir-suite"
name = "MLIR Suite"
description = "MLIR, TableGen, and PDLL with LSP support and smart highlighting."
version = "0.5.2"
schema_version = 1
authors = ["Buyun Xu <xubuyun@outlook.com>"]
repository = "https://github.com/felixtensor/zed-mlir-suite"

[grammars.mlir]
repository = "https://github.com/felixtensor/tree-sitter-mlir"
commit = "7c44caa20ab420740fa6a34d8b9426eb549b290d"

[grammars.tablegen]
repository = "https://github.com/felixtensor/tree-sitter-tablegen"
commit = "12a5db3b013b9b5ef6bc828621f9ce4fa47ad192"

[grammars.pdll]
repository = "https://github.com/felixtensor/tree-sitter-pdll"
commit = "8c7e8643acc5534b4e5316e2c97aa52a54d74faa"

[language_servers.mlir-lsp-server]
name = "mlir-lsp-server"
language = "MLIR"

[language_servers.mlir-pdll-lsp-server]
name = "mlir-pdll-lsp-server"
language = "PDLL"

[language_servers.tblgen-lsp-server]
name = "tblgen-lsp-server"
language = "TableGen"
