name = "MLIR"
grammar = "mlir"
path_suffixes = ["mlir"]
line_comments = ["//"]
word_characters = [".", "$", "@"]
autoclose_before = " \n\r\t}:)>]"

[brackets]
paired = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "<", end = ">", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false }
]
